<?php
/**
 * TODO: Package description.
 *
 * PHP version 5
 *
 * @category
 * @package
 * @author    Ilya Rubinchik <ilfate@gmail.com>
 *
 * @license   Proprietary license.
 * @link      http://ilfate.net
 */
namespace Ilfate\MageSurvival\Generators;
use Ilfate\MageSurvival\ChanceHelper;
use Ilfate\MageSurvival\Event;
use Ilfate\MageSurvival\Game;
use Ilfate\MageSurvival\GameBuilder;
use Ilfate\MageSurvival\Spell;
use Ilfate\MageSurvival\WorldGenerator;

/**
 * PHP version 5
 *
 * @category
 * @package
 * @author    Ilya Rubinchik <ilfate@gmail.com>
 * @license   Proprietary license.
 * @link      http://ilfate.net
 */
class WorldGeneratorHome extends WorldGeneratorSchool
{
    protected static $generatorConfig = [
        'world-predefined' => true,
        'full-world' =>
            array ( 0 => array ( 0 => 'f1', 1 => 'f1+1000', 3 => 'f4', 4 => 'f2', 5 => 'f4', -1 => 'f4', ), 1 => array ( 0 => 'f3', 1 => 'f4', 3 => 'f3', 4 => 'f3', 5 => 'f3', -4 => 's1', -3 => 'f2', -2 => 'f3', -1 => 'f2', ), 2 => array ( 0 => 's1', 3 => 'f2', 4 => 'f4', 5 => 'f2', -4 => 'f1+1000', -3 => 'f3', -2 => 'f4', -1 => 'f1', ), 3 => array ( 0 => 'f3', 1 => 'f4', 2 => 'f2', 3 => 'f3', 4 => 'f4', 5 => 'f1', -4 => 's1', -3 => 'f3', -2 => 'f4', -1 => 'f2', ), -4 => array ( 0 => 'f1', 1 => 'f2', -4 => 'f1', -3 => 'f4', -2 => 'f3', -1 => 'f2', ), -3 => array ( 0 => 'f3', 1 => 'f4', -4 => 'f3', -3 => 'f1+7', -2 => 'f4', -1 => 'f2', ), -2 => array ( 0 => 'f3', 1 => 'f4', 4 => 'f1+15', -4 => 'f1+7', -3 => 's1', -2 => 'f1+7', -1 => 'f2', ), -1 => array ( 0 => 'f1', 1 => 'f2', 3 => 'f2', 4 => 'f3', 5 => 'f4', -4 => 'f2', -3 => 'f1+7', -2 => 'f4', -1 => 'f3', ), )
            ,
        //'portalLocation' => ['x' => 0, 'y' => 1],
//        'dialog' => [
//            'help' => [
//                ['method' => 'tutorialMessage']
//            ], 'turn' => [
//                1 => ['message' => 'OMG what happened to my school?? Oh I found fireball spell. Who dropped it here?'],
//                3 => ['message' => 'Where is everybody? All the teachers and students are missing!'],
//                5 => ['message' => 'Ok here is the wand of one of the teachers. She is a witch.'],
//                7 => ['message' => 'Maybe I can find her? I remember that she was living in a forest.'],
//                11 => ['message' => 'I just need to get to the portal.'],
                //100 => ['message' => 'I h.'],
//            ]
//        ]
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
    }
    
}