<?php namespace Ilfate\MageSurvival\Units\Boss;

use Ilfate\MageSurvival\Game;
use Ilfate\MageSurvival\Units\Boss;

/**
 * TODO: Short description.
 * TODO: Long description here.
 *
 * PHP version 5
 *
 * @category
 * @package
 * @author    Ilya Rubinchik <ilfate@gmail.com>
 *
 * @license   Proprietary license.
 * @link      http://ilfate.net
 */
class SpiderNest extends Boss
{
    public function freeze($turns, $stage)
    {
        //parent::freeze($turns, $stage); // TODO: Change the autogenerated stub
        $this->mage->say('Wow! This nest is not freezable!', $stage);
    }
}